<?php

namespace App\Helpers;

class QuickReplies
{
    public static function getReplies($role = 'asesor')
    {
        $compartidas = [
            '/audiosnomanejamos' => "Por políticas de garantía, preferimos conversaciones en texto para resolver inquietudes y administrar mejor la información para darles más garantías. Sugerimos usar el micrófono de la app para transcribir mensajes de voz automáticamente. Agradecemos tu comprensión y estamos aquí para ayudarte. ¡Gracias por tu amabilidad! 👍🌟",
        ];

        $replies = [
            'admin' => [
                '/saludoinicial' => "Saludos🙏, somos Rapiprofe.\n\nTrabajamos solo por Whatsapp.\n\nRapiprofe es una plataforma que ofrece servicios académicos y educativos a nivel nacional y en otros 18 países de América, con más de 17 años de experiencia.👌\n\n¿Que quieres cotizar hoy? ¿tareas, trabajos universitarios, tesis de grado, monografías, artículos, ensayos, clases virtuales, curso virtual de PREICFES (pre saber) u otro?",
                
                '/50y50' => "CONDICIONES DE PAGO: \n✅ Consigna el 50% como anticipo para poder iniciar el trabajo y cuando lo tengamos listo le enviaremos evidencias (capturas de pantalla de algunas páginas). Cuando revise, nos consigna el 50% restante y se lo enviaremos por acá por Whatsapp o vía correo electrónico, como prefieras.",
                
                '/alaordencliente' => "Gracias por confiar en nosotros, será siempre un gusto atenderte 😁👍🙏🏻\n\nSi nuestros servicios le parecen efectivos, haz que más personas también logren soluciones académicas:\n\n🔸 Consulta temas relacionados con tus actividades universitarias en: https://rapiprofe.com/\n\n🔸 Síguenos en nuestras redes sociales: \n\n- Instagram:\nLink:\nhttps://instagram.com/rapiprofe\n\n- Facebook:\n@rapiprofe CO \nLink: https://n9.cl/jubry\n\n- Tiktok:\n@rapiprofe\nLink: https://n9.cl/oqhmy\n\nBendiciones 🙏",
                
                '/apanormas' => "¿Es con normas APA séptima edición?",
        
                '/aprobadoeltrabajo' => "Aprobado este trabajo por 100.000 COP, puedes iniciar 😁👏👏👏. Recuerda la puntualidad en la entrega del mismo 👌\n\n¡Recuerda!\nREGLAS PARA RAPIPROFES ALIADOS:\n1) Para ejercicios, trabajos, anteproyectos, monografías, tesis, taller o afines, se debe atender las correcciones que tengan lugar, siempre y cuando estas se ajusten a los lineamientos indicados inicialmente por el cliente. 👌\n2) Luego de ser calificados o revisados los trabajos o pruebas (asistencia en línea) que entreguemos al cliente; si resulta que éste nos envía evidencias claras de pérdida de la nota, es decir, si obtiene resultados inferiores a 3.0; o al 60% de los puntos y nos soporta, debe efectuar la devolución del 70% del dinero cobrado 🤝\n3) Los trabajos deben cumplir con un mínimo de plagio establecido, si el trabajo es considerado fiel copia o rechazado por plagio ud como el encargado de la elaboración debe responder por las consecuencias derivadas de esto.\n4) Si el servicio no es entregado por parte de Ud. justo en la fecha y hora acordados, no se le podrá pagar ya que el cliente tampoco nos pagará por el servicio retrasado. Si hay la posibilidad de conciliar con el cliente y este último consigue un plazo con su docente, como pago Ud. recibirá el 70% del valor total del servicio, si y sólo si nos lo entrega conforme.\n\nEl presente servicio no genera relación laboral entre las partes, sometiéndose a ellos de manera libre, expresa y voluntaria, en consecuencia, no habrá lugar a reconocimiento y pago de ninguna prestación social. Expresa independencia para cumplir el objeto del servicio y únicamente está sometido a los manuales éticos de su profesión.\n\nQue tengas mucho éxito 👌🙏",
        
                '/atentocliente' => "El precio que le estamos ofreciendo se mantiene fijo durante las próximas 24 horas. Después de este tiempo, podría tener alguna modificación.\n\nEstamos aquí, listos y atentos, para cerrar el trato contigo. ¡Estamos a tu disposición! 👌😉",
        
                '/atentorapiprofe' => "Hola, cuánto me cobras por este trabajo que es para entregar el \nQuedo pendiente y agradezco mucho la atención y pronta respuesta 🤝👌",
        
                '/audiosnomanejamos' => "\"Por políticas de garantía, preferimos conversaciones en texto para resolver inquietudes y administrar mejor la información para darles más garantías. Sugerimos usar el micrófono de la app para transcribir mensajes de voz automáticamente. Agradecemos tu comprensión y estamos aquí para ayudarte. ¡Gracias por tu amabilidad! 👍🌟\"",
                
                '/calificanos' => "\"Te agradecemos mucho y sería genial si calificas nuestro servicio aquí 👇\nhttps://g.co/kgs/tiYcUy\"",
                
                '/confiables' => "\"¡No se preocupe! Somos una empresa confiable y estamos aquí para ayudarle, asegurándonos de que quede completamente satisfecho con nuestro trabajo. 💪 Queremos construir una relación de confianza que fomente la fidelización, buscando la continuidad y, aún mejor, que nos recomiende con sus compañeros de estudio, amigos y familiares. 🌟\nEsto es más que un trabajo para nosotros, ¡es nuestra razón de ser! 🌈 No buscamos engañar a nadie, nuestro objetivo es ganar clientes día a día y prosperar con la ayuda de Dios. 🙏 Confíe en nosotros para brindarle el mejor servicio. ¡Estamos aquí para usted! 🤝😊\"",
                
                '/congustoguardaminumero' => "\"Con gusto, para servirte siempre.\nRecuerda que estaremos por acá 24/7 para ayudarte en toda clase de trabajos académicos.\nPor favor guarda nuestros números de WhatsApp\"",
                
                '/congustoteayudamos' => "\"Claro que sí, con gusto te ayudamos\"",
                
                '/consignaelrestodeldinero' => "\"Hola, ¿cómo vas? Bendiciones 🙏.\nEs para comunicarte que el trabajo está terminado, por favor consigna el resto del dinero para enviarte. \nQuedo atento al soporte de pago. 👌\nYa te mando evidencias:\"",
                
                '/correcciones' => "\"Ok, por favor envíame el documento con las observaciones de tu profe para cotizarte\"",
                
                '/enquetepuedoayudar' => "\"Hola, ¿cómo vas?\n¿En qué te podemos ayudar hoy?\"",
                
                '/ensayodatos' => "\"Claro que sí, con gusto te cotizamos 👌\n¿Cuántas páginas debe tener?\n¿Tienes el tema definido?\n¿Es con normas APA séptima edición?\nPara darte precio\"",
                
                '/estudiasquecarretaytema' => "\"¿Qué estudias?\n¿Ya tienes un tema definido?\nPara darte precio\"",
                
                '/fechadeentregadelservicio' => "\"¿Cuál es la fecha de entrega del trabajo?\"",
                
                '/garantías' => "\"GARANTÍAS:\n✅ Experiencia en el mercado y más de 18.000 clientes satisfechos con nuestros servicios.\n✅ Nos comprometemos a entregar un trabajo de alta calidad, cuidadosamente redactado con las normas exigidas por tu universidad.\n✅ Garantía anti plagio y detección de inteligencia artificial para garantizar la originalidad y autenticidad del contenido. \n✅ Aprobación garantizada. Con nosotros tienes derecho a correcciones gratuitas durante 30 días posteriores a la entrega, asegurando así tu plena satisfacción con nuestro trabajo. \nCabe anotar que estas correcciones y revisiones no generan costos adicionales siempre y cuando correspondan a lo cotizado y realizado por nuestra parte; ¡de esta manera quedarás satisfecho con el producto recibido!\n✅ Puntualidad en la entrega.\"",
                
                '/gestorasteatienden' => "\"Claro que sí. Con gusto te ayudamos\nYa pasamos tu contacto a una de nuestras Gestoras expertas, identificada en WhatsApp con el perfil de Rapiprofe. Ella en breve te escribirá.\nPor favor, proporciona la información que ella te solicite para que pueda cotizarte en el menor tiempo posible. 🤝\"",
                
                '/graciascliente' => "\"¡Muchas gracias por preferirnos! Esperamos poder servirte nuevamente.\"",
                
                '/graciasrapiprofe' => "\"Muchas gracias 👏👏👏.\nYa entrego y gestiono el pago 👌\"",
                
                '/gradoomateria' => "\"¿Es para grado o es para una materia de la universidad?\"",            
                
                '/informacionparacotizarte' => "\"Hola, ¿cómo estás?\nQuedo atento a la información para poder cotizar el trabajo 👌\"",
                
                '/iniciarquedoatentoalpago' => "\"Quedo atento al pago para iniciar 🤝👌\"",
        
                '/iniciar50%' => "\"Podemos iniciar con el 50%\"",
                
                '/monografiaenCOP' => "\"COTIZACIÓN PARA LA ELABORACIÓN.\nEl trabajo será realizado por un profesional graduado en el área: \nMonografía para pregrado: 990.000 COP \n(tiempo de entrega: el acordado entre ambas partes).\n\nGARANTÍAS:\n✅ Experiencia en el mercado y más de 18.000 clientes satisfechos con nuestros servicios.\n✅ Nos comprometemos a entregar un trabajo de alta calidad, cuidadosamente redactado con las normas exigidas por tu universidad.\n✅ Garantía anti plagio y detección de inteligencia artificial para garantizar la originalidad y autenticidad del contenido. \n✅ Aprobación garantizada. Con nosotros tienes derecho a correcciones gratuitas durante 30 días posteriores a la entrega, asegurando así tu plena satisfacción con nuestro trabajo. \nCabe anotar que estás correcciones y revisiones no generan costos adicionales siempre y cuando correspondan a lo cotizado y realizado por nuestra parte; ¡de esta manera quedarás satisfecho con el producto recibido!\n✅ Puntualidad en la entrega.\n\nCONDICIONES DE PAGO: \n✅ Consigna el 50% como anticipo para poder iniciar el trabajo y cuando lo tengamos listo le enviaremos evidencias (capturas de pantalla de algunas páginas). Cuando revise, nos consigna el 50% restante y se lo enviaremos por acá por Whatsapp o vía correo electrónico, como prefieras.\n\nPolíticas de correcciones de Rapiprofe: https://n9.cl/2i4h8\n\nSi estás de acuerdo, por favor confírmanos y realiza el pago en los medios indicados al pie 👇\nNo olvides mandarnos la foto del soporte de pago listo! 🎞.\"",
                
                '/monografiaUSDprecio' => "\"COTIZACIÓN PARA LA ELABORACIÓN.\nEl trabajo será realizado por un profesional graduado en el área: \n✅ Tesis, proyecto, trabajo de prácticas, monografía de grado:\nMonografía para pregrado: 299 dólares  \n(tiempo de entrega: el acordado entre ambas partes).\n\nGARANTÍAS:\n✅ Experiencia en el mercado y más de 18.000 clientes satisfechos con nuestros servicios.\n✅ Nos comprometemos a entregar un trabajo de alta calidad, cuidadosamente redactado con las normas exigidas por tu universidad.\n✅ Garantía anti plagio y detección de inteligencia artificial para garantizar la originalidad y autenticidad del contenido. \n✅ Aprobación garantizada. Con nosotros tienes derecho a correcciones gratuitas durante 30 días posteriores a la entrega, asegurando así tu plena satisfacción con nuestro trabajo. \nCabe anotar que estás correcciones y revisiones no generan costos adicionales siempre y cuando correspondan a lo cotizado y realizado por nuestra parte; ¡de esta manera quedarás satisfecho con el producto recibido!\n✅ Puntualidad en la entrega.\n\nCONDICIONES DE PAGO: \n✅ Consigna el 50% como anticipo para poder iniciar el trabajo y cuando lo tengamos listo le enviaremos evidencias (capturas de pantalla de algunas páginas). Cuando revise, nos consigna el 50% restante y se lo enviaremos por acá por Whatsapp o vía correo electrónico, como prefieras.\n\nPolíticas de correcciones de Rapiprofe: https://n9.cl/2i4h8\n\nSi estás de acuerdo, por favor confírmanos y realiza el pago en los medios indicados al pie 👇\nNo olvides mandarnos la foto del soporte de pago listo! 🎞.\"",
                
                '/novedadesdenominaprimeraquincena' => "\"NOVEDADES DE NOMINA PRIMERA QUINCENA RAPIPROFE\nBuenos días y venzamos hoy, mañana y por siempre, en el nombre de Jesús 🙏\n\nReporte de Novedades de Nómina RAPIPROFE: Quincena del 1 al 15 de --- de 2025 son:\n\nRoberny Rocio:\nHoras extras ordinarias: No\nHoras dentro del turno de trabajo laboradas el domingo: 6.\nHoras Festivas laboradas dentro del turno de trabajo: N.A.\nBono por cumplimiento: N.A.\nAuxilio de conectividad: 50% esta quincena.\n\nFloryerick Ollarves:\nHoras extras ordinarias: No\nHoras dentro del turno de trabajo laboradas domingo: 6.\nHoras Festivas laboradas dentro del turno de trabajo: N.A.\nBono por cumplimiento: N.A.\nAuxilio de conectividad: 50% esta quincena.\n\nRosa Iglesias:\nHoras extras ordinarias: No\nHoras dentro del turno de trabajo laboradas el domingo: 12.\nHoras Festivas laboradas dentro del turno de trabajo: N.A.\nBono por cumplimiento: N.A.\nAuxilio de conectividad: 50% esta quincena.\n\nGracias 😁👍\"",
                
                '/novedadesdenominasegundaquincena' => "\"NOVEDADES DE NOMINA SEGUNDA QUINCENA RAPIPROFE\nBuenos días y venzamos hoy, mañana y por siempre, en el nombre de Jesús 🙏\n\nReporte de Novedades de Nómina RAPIPROFE: Quincena del 16 al 30 de --- de 2025 son:\n\nRoberny Rocio:\nHoras extras ordinarias: No\nHoras dentro del turno de trabajo laboradas el domingo: 6.\nHoras Festivas laboradas dentro del turno de trabajo: N.A.\nBono por cumplimiento: 200.000 COP.\nAuxilio de conectividad: 50% esta quincena.\n\nFloryerick Ollarves:\nHoras extras ordinarias: No\nHoras dentro del turno de trabajo laboradas domingo: 6.\nHoras Festivas laboradas dentro del turno de trabajo: N.A.\nBono por cumplimiento: 200.000 COP.\nAuxilio de conectividad: 50% esta quincena.\n\nRosa Iglesias:\nHoras extras ordinarias: No\nHoras dentro del turno de trabajo laboradas el domingo: 12.\nHoras Festivas laboradas dentro del turno de trabajo: N.A.\nBono por cumplimiento: 200.000 COP.\nAuxilio de conectividad: 50% esta quincena.\n\nGracias 😁👍\"",
            ],
            'asesor' => [
                // Respuestas para Asesores
                '/rapiprofenuevo' => "Si quieres pertenecer al grupo selecto de Rapiprofes, por favor escribe al administrador de la plataforma 👇\nhttps://wa.me/573104193581 \nBendiciones 🙏",
        
                '/guardaminumero' => "Por favor, antes de continuar, guardas este número en contactos para que no me bloqueen 🙌",
        
                '/atento' => "El precio que le estamos ofreciendo se mantiene fijo durante las próximas 24 horas. Después de este tiempo, podría tener alguna modificación.\n\nEstamos aquí, listos y atentos, para cerrar el trato contigo. ¡Estamos a tu disposición! 👌😉",
        
                '/antiplagio' => "Hola, con la entrega de cada trabajo, por favor, adjuntar el informe de plagio (en PDF o Word); \n\nTe recomendamos usar dos que son gratis 👇:\n\nPara pocas páginas (escanea 3 páginas a la vez, más o menos 1.000 palabras). Es muy bueno.\n\n1. https://plagiarismdetector.net/\n\n2. https://www.duplichecker.com/es\n\nEjemplo:\nTexto: https://docs.google.com/document/d/1IFLRikbtTQvBeFuSvPGaEZhuhXIucrY2/edit?usp=share_link&ouid=109872177303615641446&rtpof=true&sd=true\nReporte de plagio: https://drive.google.com/file/d/1tUFdrBnzRFaT4oyOZ3LoVM8Zw4P8CmXM/view?usp=share_link\n\n\nPara trabajos más extensos (escanea hasta 80 páginas por turno).\n\n3. http://antiplagiarism.net/downloads/en/antiplagiarism.zip\n\nEste programa se descarga al PC y se conecta automático a internet (debes estar conectado a una red wifi o datos).",
        
                '/síguenos' => "🔸 Síguenos en nuestro sitio web:\nhttps://rapiprofe.com/\n\n🔸 Podrás encontrarnos también en nuestras redes sociales: \n\n- Instagram:\nLink:\nhttps://instagram.com/rapiprofe\n\n- Facebook:\n@rapiprofe CO \nLink: https://n9.cl/jubry\n\n- Tiktok:\n@rapiprofe\nLink: https://n9.cl/oqhmy\n\nBendiciones 🙏",
        
                '/recomiendanos' => "Hola cómo estás? 🖐🏻\n\nSomos Rapiprofe 😃\nRecuerda que por acá te ayudamos con tareas, trabajos, tesis, proyectos, clases online, etc. \nhttps://rapiprofe.com/\n\nSi has recibido ayuda de esta plataforma de asesorías, por favor recomiéndanos con tus compañeros de clase, familiares y amigos así nos ayudas a crecer y te podremos ofrecer mejores precios la próxima vez👌👏❤\n\nEnvíales mi link directo de WhatsApp:\n\nhttps://wa.me/573012792025\n\nMuchas gracias de antemano 🙏",
        
                '/devoluciondeldinerodatos' => "Las devoluciones de dinero solo se realizarán a través de los siguientes medios de pago:\n🔸 Cuenta de ahorros, ahorro a la mano o corriente de Bancolombia.\n🔸 Nequi \n🔸 Efecty (giros nacionales para Colombia); para lo cual por favor nos regala la siguiente información:\n▪Numero de cuenta (especificar si es de ahorros o corriente).\n▪Nombre completo \n▪Numero de cédula de ciudadania.\n🔸 Paypal (nos regala dirección de correo electrónico).\n\nMuchas gracias, bendiciones 🙏",
        
                '/perdonporhacerteperderlano' => "¡Mil disculpas por cualquier inconveniente y la pérdida de la nota! 🙏 No era nuestra intención causarte problemas. De todas formas, tras esta situación, evaluaremos la situación con este asesor en la empresa y nos esforzaremos al máximo para ayudarte a recuperar tu promedio de notas. 💼\n\nEstamos comprometidos a reivindicarnos contigo en los próximos trabajos y pruebas. ¡Confía en nosotros, estoy seguro de que nos irá excelente! 👍 ¡Estamos aquí para apoyarte en todo momento! 🌟",
        
                '/transfiyaorecarga' => "Hola 🖐🏻, para pagar desde un banco distinto al enviado en las fotos puedes hacerlo por dos medios: \n\n1. Por Transfiya\n\n2. Por recarga nequi a través de este link: https://recarga.nequi.com.co/bdigitalpsl/#!/\n\nAl siguiente número: 3104193581\n\nGracias ☺",
        
                '/audiosnomandesporfavor' => "\"Por políticas de garantía, preferimos conversaciones en texto para resolver inquietudes y administrar mejor la información para darles más garantías. Sugerimos usar el micrófono de la app para transcribir mensajes de voz automáticamente. Agradecemos tu comprensión y estamos aquí para ayudarte. ¡Gracias por tu amabilidad! 👍🌟\"",
        
                '/seguimientodecotizacion' => "¡Hola! 👋 ¿Qué te pareció la cotización para el servicio académico que pediste? 💰¿Estás satisfecho o necesitas un descuento? 😊📚\n\nQuedamos atentos para ayudarte 👌",
        
                '/horario' => "En este momento está abierto\nNuestro horario comercial es el siguiente:\nSábado: Abierto 24 horas\nDomingo: Abierto 24 horas\nLunes: Abierto 24 horas\nMartes: Abierto 24 horas\nMiércoles: Abierto 24 horas\nJueves: Abierto 24 horas\nViernes: Abierto 24 horas",
        
                '/hoymismono' => "¡Oops! 😬 Lamentamos informarte que no podemos ofrecer el servicio para el mismo día o en unas cuantas horas. 🚫 Necesitamos al menos un día de anticipación, o incluso más, dependiendo de la extensión del trabajo o de los temas para las tutorías o las asistencias en línea.\n\nLa buena noticia es que ya hemos establecido contacto y estamos seguros de que te ayudaremos en tu próximo requerimiento. 🌟\n\n¡No olvides guardar nuestro número y conservar este chat! Estaremos disponibles para futuros servicios de asesoría. 📲💬 ¡Esperamos tu próxima consulta! 👋😊",
        
                '/recibidopago' => "Recibido el pago 👌puedes contar con el servicio en la fecha y hora acordados 😉 👍",
        
                '/formularioporWA' => "Si tienes inconvenientes para diligenciar el formulario, por favor regálame estos datos completos:\n\n1. Carrera que estudias:\nMateria:\n2. Fecha y hora máxima de entrega:\n3. Si es examen, cuántas horas dura: \n4. Documentos, apuntes, fotos, etc.:\n5. Especificaciones adicionales a tener en cuenta en el servicio:\n6. Correo electrónico:\n\nMuchas gracias, quedo atenta 👌.",
        
                '/formulariodecotizacion' => "Hola, bendiciones 🙏\nBienvenid@ a RAPIPROFE, \n\"Tu mejor solución académica\"\n\n👋 Mi nombre es Nombre. Hoy seré la encargada de cotizarte y prestarte el servicio. (Tareas, trabajos, parciales, quiz, trabajo de grado, etc.).\n\n👋 Ayúdanos a darte la mejor cotización en el menor tiempo posible enviándonos los datos requeridos. 👇\nhttps://rapiprofe.com/\n\nEn breve te ofreceremos el mejor precio 👌.\n\nMil gracias, quedo atenta 😄🤝",
        
                '/formularioincompleto' => "Hola, bendiciones 🙏🏻\nEl equipo de Rapiprofe ha comprobado que nos solicitaste servicios académicos desde nuestro link.\n\nSin embargo para poder darte precio necesitamos que nos envíes por acá por Whatsapp los archivos o imágenes relacionados con el servicio (enunciado del trabajo, ejercicios, plantilla, estructura, rubrica, fotos o capturas, etc).\n\nQuedamos atentos 👌.",
        
                '/datosasistenciaenlinea' => "Por favor me facilitas estos datos para darte precio:\n\n1. Temas puntuales a evaluar y material de apoyo o ejemplos (capturas de pantalla, apuntes, fotos, guías, exámenes anteriores sobre el mismo tema, etc).\n2. Tipo de examen, parcial, prueba o taller (seleccion multiple, respuestas abiertas o cerrada, con o sin procedimientos, etc.).\n3. Cantidad de preguntas\n4. ¿Cuánto tiempo dura la prueba/examen/parcial/taller?",
        
                '/datoswesternunion' => "Datos para el pago por Western Union o en otra Remesadora\n\nNombre: Javier Alfonso \nPrimer apellido: Alguero \nSegundo apellido: Jiménez \nDocumento de identidad número: 5164608\nCorreo electrónico: rapiprofe1@gmail.com\nDireccion: Carrera 38d # 32 67 Barrio costa hermosa \nCiudad: Soledad\nDepartamento: Atlántico \nCodigo Postal: 080003\nPais: Colombia\nNumero de celular: ‪+573104193581‬‬\nPropósito de transacción: concepto 1809: Remesas de trabajadores (ayuda económica y asesorías académicas)\n\nOtras Remesadoras en Latinoamérica\n\n- MoneyGram\n- DoIEx\n- Remitly\n- Uno\n- VIAMERICAS\n- TRANFAST\n- South Exchange\n- Ria\n- La Nacional\n- La Caixa (Banco)\n- Worldremit\n- Wellsfargo\n- Xoom\n- Uniteller\n- PNC (Global Transfers)\n- More\n- Wise\n- Terrapay\n- Vigo",
        
                '/pagosporpaypal' => "Cómo enviar dinero a Rapiprofe por Paypal: 👇\n\nhttps://drive.google.com/file/d/1lD90uwP3ZJg4Qe5dVb73uQHk2LRWPjzo/view?usp=sharing\n\nNuestra cuenta Paypal : rapiprofe1@gmail.com.",
        
                '/pagar' => "Favor, cancelar -00mil COP a -NOMBRE- CODIGO",
        
                '/tutorialogisticarapiprofe' => "La logística que manejaremos para la tutoría en línea será así: \n🔸 Nos mandas el link o enlace de la reunión para la clase por el medio escogido por el estudiante (Zoom, Google meet, TeamViewer, etc).\n🔸 Nosotros le enviaremos al cliente dicho link y estaremos en la reunión con el cliente. \n🔸 Importante: todos los asuntos distintos a la tutoría, se resuelven desde esta línea exclusivamente.\n¡Bendiciones! 🙏😉👌",
        
                '/tutorialogisticacliente' => "La logística que manejaremos para la tutoría en línea será así: \n🔸 Escoges el medio por el cual puedes o quieres recibir la asesoría para definir con el profe (Zoom, Google meet, TeamViewer, etc).\n🔸 Después de definir con el profe, te enviaremos el link o enlace de la reunión para la clase. Estaremos presentes en la reunión con el profe. \n🔸 Importante: todos los asuntos distintos a la tutoría, se resuelven desde esta línea exclusivamente.\n¡Bendiciones! 🙏😉👌",
        
                '/asistenlinealogistrapipro' => "La logística que manejaremos para la asistencia en línea será así: \n🔸Crearé un grupo de 3 personas por WhatsApp (El cliente, Ud. y mi persona. Solo se admiten estos 3 integrantes). Le enviaremos el nombre del grupo o el enlace para que se una al mismo. Al cliente lo añadiremos justo antes de la prueba.\n🔸 El cliente enviará al grupo, fotos bien claras o los archivos del enunciado de la prueba y dependiendo de la forma de la evaluación Ud. irá enviando los desarrollos o respuestas una a una para que el cliente vaya anotando o adjuntando o si es el caso, el desarrollo completo antes de agotarse el tiempo de la prueba. \n🔸 Importante: todos los asuntos distintos a la prueba en sí, se resuelven desde esta línea exclusivamente.\n¡Bendiciones! 🙏😉👌",
        
                '/asistenlinealogistcliente' => "La logística que manejaremos para la asistencia en línea de su parcial, quiz o taller, será: \n🔸15 minutos antes de la prueba crearé un grupo de 3 personas por WhatsApp (El Rapiprofe, Ud. y mi persona. Solo se admiten estos 3 integrantes). Le enviaremos el enlace para que se una o el nombre del grupo.\n🔸Nos envías al grupo, fotos bien claras o los archivos enunciados de la prueba; a su vez, nosotros estaremos enviando punto por punto las soluciones - desarrollos para que vayas pasando o adjuntando y si amerita, enviaremos todo completo al final, antes de agotarse el tiempo de la prueba. \n🔸 Importante: no se puede tocar tema de precios ni tampoco renegociar dentro del grupo, esos asuntos se resuelven desde esta línea exclusivamente.\n¡Bendiciones! 🙏😉👌",
        
                '/aprobadatutoriaenlinea' => "¡Listo! aprobada la tutoría en línea por 100.000 COP (2 horas) 😁. Puedes agendar este servicio 👏👏👏. Recuerda enviarnos el enlace o link de la reunión y estar puntualmente en línea el día y hora acordados👌.",
        
                '/aprobadaasistenciaenlinea' => "¡Listo! aprobada la asistencia en línea para esta prueba por 100.000 pesos colombianos 😁. Puedes agendar este servicio 👏👏👏. Recuerda estar puntualmente en línea el día y hora acordados 👌.\n\n¡Recuerda!\n\nREGLAS PARA RAPIPROFES ALIADOS:\n1) Para ejercicios, trabajos, anteproyectos, monografías, tesis, taller o afines, se debe atender las correcciones que tengan lugar, siempre y cuando estas se ajusten a los lineamientos indicados inicialmente por el cliente. 👌\n2) Luego de ser calificados o revisados los trabajos o pruebas (asistencia en línea) que entreguemos al cliente; si resulta que éste nos envía evidencias claras de perdida de la nota, es decir, si obtiene resultados inferiores a 3.0; o al 60% de los puntos y nos soporta, debe efectuar la devolución del 70% del dinero cobrado 🤝\n3) Si el servicio no es entregado por parte de Ud. justo en la fecha y hora acordados, no se le podrá pagar ya que el cliente tampoco nos pagará por el servicio retrasado. Si hay la posibilidad de conciliar con el cliente y este último consigue un plazo con su docente, como pago Ud. recibirá el 70% del valor total del servicio, si y solo si nos lo entrega conforme.\n\nEl presente servicio no genera relación laboral entre las partes, sometiéndose a ellos de manera libre, expresa y voluntaria, en consecuencia, no habrá lugar a reconocimiento y pago de ninguna prestación social. Expresa independencia para cumplir el objeto del servicio y únicamente está sometido a los manuales éticos de su profesión.\n\nQue tengas mucho éxito 👌🙏",
        
                '/aprobadoeltrabajoinicio' => "Aprobado este trabajo por 100.000 COP, puedes iniciar 😁👏👏👏. Recuerda la puntualidad en la entrega del mismo 👌\n\n¡Recuerda!\n\nREGLAS PARA RAPIPROFES ALIADOS:\n1) Para ejercicios, trabajos, anteproyectos, monografías, tesis, taller o afines, se debe atender las correcciones que tengan lugar, siempre y cuando estas se ajusten a los lineamientos indicados inicialmente por el cliente. 👌\n2) Luego de ser calificados o revisados los trabajos o pruebas (asistencia en línea) que entreguemos al cliente; si resulta que éste nos envía evidencias claras de pérdida de la nota, es decir, si obtiene resultados inferiores a 3.0; o al 60% de los puntos y nos soporta, debe efectuar la devolución del 70% del dinero cobrado 🤝\n3) Los trabajos deben cumplir con un mínimo de plagio establecido, si el trabajo es considerado fiel copia o rechazado por plagio ud como el encargado de la elaboración debe responder por las consecuencias derivadas de esto.\n4) Si el servicio no es entregado por parte de Ud. justo en la fecha y hora acordados, no se le podrá pagar ya que el cliente tampoco nos pagará por el servicio retrasado. Si hay la posibilidad de conciliar con el cliente y este último consigue un plazo con su docente, como pago Ud. recibirá el 70% del valor total del servicio, si y sólo si nos lo entrega conforme.\n\nEl presente servicio no genera relación laboral entre las partes, sometiéndose a ellos de manera libre, expresa y voluntaria, en consecuencia, no habrá lugar a reconocimiento y pago de ninguna prestación social. Expresa independencia para cumplir el objeto del servicio y únicamente está sometido a los manuales éticos de su profesión.\n\nQue tengas mucho éxito 👌🙏",
        
                '/plataformaprocesosyreglas' => "Proceso de cotización y reglas para las materias en plataformas virtuales con RAPIPROFE:\n🔸Por favor nos regalas el link de la página de la universidad, su usuario y contraseña para revisar la(s) materia(s) solicitada(s), revisar los contenidos y gestionarle la cotización. Es necesario conocer el número de actividades (trabajos, quiz, parciales, foros, en fin) para poder dar un precio.\n🔸Si en la plataforma aún no se encuentran activas o visibles las actividades y evaluaciones, no sería posible cotizar, debemos evitar a toda costa las suposiciones. En este caso si las actividades evaluativas van apareciendo en el transcurso del periodo académico, se tendrán que ir cotizando una a una.\n🔸Tenga en cuenta que hay plataformas que, si se abren desde otra ciudad o país, al acceder arrojan ciertas preguntas de seguridad, por eso, requerimos que esté atento para que nos envíe las respectivas respuestas cada vez que el asesor vaya a ingresar.\n🔸Si el ingreso de nuestro asesor a la plataforma, representa problemas para Ud. en su universidad por tener una IP diferente, la solución es que nos mandes toda la información por medio de WhatsApp o Telegram, es decir, los enunciados de los trabajos con antelación para resolverlos y hacer las pruebas (quiz y parciales) en línea por medio de WhatsApp o Telegram con ayuda del asesor.\n🔸Es necesario que nos avise o nos recuerde con días de anticipación de la fecha de entrega de las diferentes actividades, con el fin de recordarle al tutor también y poder presentar todo a tiempo y cumplir a cabalidad cada una de ellas.\n🔸PAGOS: Las materias virtuales completas, se pagarán en 2 (dos) cuotas así: el 50% del valor total para iniciar y el 50% restante cuando se haya realizado la mitad de las actividades.\n\nQuedamos atentos, para ayudarte con tu trabajo, muchas bendiciones 🙏",
        
                '/plataformacotizametutor' => "¡Buenas, por favor nos cotizas una materia virtual! 👌\n\nLa idea es que acceda a la plataforma y me ofrezca un precio especial por la materia completa. Cuando ingrese, por favor, nos dice cuantas actividades hay y cuál es el valor global que nos cobra.\n\nEl pago se lo haríamos en 2 (dos) partes así: el 50% del valor total cuando entregues la mitad de las actividades; el otro 50% justo al finalizar satisfactoriamente todas las actividades.\n\nLos datos de acceso se los enviamos a continuación y también la(s) materia(s) a cotizar:",
        
                '/preciotutoriaenlinea' => "Hola, la tutoría solicitada para esta materia y estos temas te cuesta 30.000 COP por hora, o sea, en total 60.000 COP las 2 horas\n\nSi aceptas el trato, confía que estaremos en línea el día y hora acordados para asesorarte👌\n\nNo olvides que el pago es anticipado por medios indicados en la foto azul para apartar el cupo del tutor 👇\n\nPor favor, ¡mandarnos la foto del soporte de pago listo! 🎞\n\n¡Importante!: Los datos que debe contener el soporte de la transferencia electrónica son:\n🔸Banco o app origen y destino (si es por la misma app queda claro por la razón social o los logotipos y colores del soporte.\n🔸Número y tipo de cuenta de Rapiprofe o número de celular o nombre o cédula.\n🔸Valor enviado.\n🔸Debe haber una expresión que indique que el pago fue realizado como: Transferencia realizada, Envió realizado, Bien hecho, pago o transacción exitosa, etc.\n🔸Número de comprobante o referencia de la transacción (un código o nuestra cédula).\n🔸Fecha y hora de la transferencia.\nSi el soporte carece de esta información no será tomado como válido.",
        
                '/precioasistenciaenlinea' => "Hola, la asistencia en línea por medio de WhatsApp, para esta prueba te cuesta 100.000 pesos colombianos\n\nSi aceptas el trato, confía que estaremos en línea el día y hora acordados para ayudarte👌\n\nNo olvides que el pago es anticipado por medios indicados en la foto azul para apartar el cupo del tutor 👇\n\nPor favor, mandarnos la foto del soporte de pago listo🎞\n¡Importante!: Los datos que debe contener el soporte de la transferencia electrónica son:\n🔸Banco o app origen y destino (si es por la misma app queda claro por la razón social o los logotipos y colores del soporte.\n🔸Número y tipo de cuenta de Rapiprofe o número de celular o nombre o cedula.\n🔸Valor enviado.\n🔸Debe haber una expresión que indique que el pago fue realizado como: Transferencia realizada, Envió realizado, Bien hecho, pago o transacción exitosa, etc.\n🔸Numero de comprobante o referencia de la transacción (un código o nuestra cedula).\n🔸Fecha y hora de la transferencia.\nSi el soporte carece de esta información no será tomado como válido.",
        
                '/preciodeplataformavirtual' => "Hola, la/s actividad/es o materia/s en tu plataforma virtual, la/s hacemos por 100mil pesos colombianos\n\nTe lo entregaremos con la mejor calidad en el tiempo estipulado 👌\n\nSi estás de acuerdo, por favor confírmanos y realiza el pago anticipado en los medios indicados en la foto azul para iniciarlo 👇\n\nNo olvides mandarnos la foto del soporte de pago listo! 🎞\n\nImportante!: Los datos que debe contener el soporte de la transferencia electrónica son:\n🔸Banco o app origen y destino (si es por la misma app queda claro por la razón social o los logotipos y colores del soporte.\n🔸Numero y tipo de cuenta de Rapiprofe o numero de celular o nombre o cedula.\n🔸Valor enviado.\n🔸Debe haber una expresión que indique que el pago fue realizado como: Transferencia realizada, Envió realizado, Bien hecho, pago o transacción exitosa, etc.\n🔸Numero de comprobante o referencia de la transacción (un código o nuestra cedula).\n🔸Fecha y hora de la transferencia.\nSi el soporte carece de esta información no será tomado como válido.",
        
                '/preciodeltrabajoes' => "*COTIZACION PARA LA ELABORACION. *\n\nEl trabajo será realizado por un Rapiprofe experto en el área: \n\n✅ Precio: 100.000 COP\n\nGARANTIAS:\n\n✅ Experiencia en el mercado y más de 18.000 clientes satisfechos con nuestros servicios.\n\n✅ Aprobación garantizada: tienes derecho a correcciones y revisiones en el trabajo enviado sin costos adicionales siempre y cuando correspondan a lo cotizado y realizado por nuestra parte; ¡de esta manera quedarás satisfecho con el producto recibido!\n\n✅ Garantía antiplagio.\n\n✅ Puntualidad en la entrega.\n\nCONDICIONES DE PAGO:\n\n✅ El pago es anticipado.\n\nSi estás de acuerdo, por favor confírmanos y realiza el pago en los medios indicados al pie 👇\n\n¡No olvides mandarnos la foto del soporte de pago listo! 🎞.\n\nImportante!: Los datos que debe contener el soporte de la transferencia electrónica son:\n🔸Banco o app origen y destino (si es por la misma app queda claro por la razón social o los logotipos y colores del soporte.\n🔸Número y tipo de cuenta de Rapiprofe o número de celular o nombre o cedula.\n🔸Valor enviado.\n🔸Debe haber una expresión que indique que el pago fue realizado como: Transferencia realizada, Envió realizado, Bien hecho, pago o transacción exitosa, etc.\n🔸Numero de comprobante o referencia de la transacción (un código o nuestra cedula).\n🔸Fecha y hora de la transferencia.\nSi el soporte carece de esta información no será tomado como válido.",
        
                '/consignael50porciento' => "CONDICIONES DE PAGO: \n✅ Consigna el 50% como anticipo para poder iniciar el trabajo y cuando lo tengamos listo le enviaremos evidencias (capturas de pantalla de algunas páginas). Cuando revise, nos consigna el 50% restante y se lo enviaremos por acá por Whatsapp o vía correo electrónico, como prefieras.",
        
                '/mensajedebienvenida' => "Hola, bendiciones 🙏\nBienvenid@ a RAPIPROFE,\n\"Tu mejor solución académica\"\n\n👋 Mi nombre es nombre. Hoy seré la encargada de cotizarte y prestarte el servicio.\n\nPor favor regálame estos datos completos:\n\n1 Carrera que estudias:\n2 Materia:\n3 Fecha y hora máxima de entrega:\n4 Si es examen, cuántas horas dura: \n5 Documentos, apuntes, fotos, etc:\n6 Especificaciones adicionales a tener en cuenta en el servicio:\n7 Correo electrónico: \n\nQuedo atenta 😉👍",
        
                '/graciasporelcumplimiento' => "Muchas gracias por el cumplimiento. 😁👍. Esperamos contar con Ud. para realizar muchos más servicios académicos.\n\nQue tengas mucho éxito, bendiciones 👌🙏",
        
                '/graciasprofeporresponder' => "Ok, entendemos. De todas maneras muchas gracias por responder, muy amable 😉. Más adelante más trabajos 👌",
        
                '/gracias' => "¡Muchas gracias por preferirnos! Esperamos poder servirte nuevamente.",
        
                '/graciasporllenarelformula' => "Hola, bendiciones 🙏🏻\nEl equipo de Rapiprofe ha comprobado que nos solicitaste servicios académicos a través de nuestras plataformas.\n\nYa estamos gestionando con varios profes para ofrecerte el mejor precio en el menor tiempo posible. En contados minutos te daremos la cotización del servicio 👌\n\nEs muy importante que la información este completa, además, revisa 👇\n\n✅ Reglas de servicios académicos: https://n9.cl/e4zb5\n\n✅ Política de correcciones: https://n9.cl/2i4h8",
        
                '/graciasprofexcotizarelser' => "Muchas gracias por la cotización; vamos a gestionar!. Si el cliente acepta, le confirmare enviándole un mensaje de aprobación en el menor tiempo posible.\n\nIgual sí el cliente no acepta, no importa; pronto habrán mas servicios 👌🙏"
            ],
        ];

        if (isset($replies[$role])) {
            return array_merge($compartidas, $replies[$role]);
        }

        return $compartidas;
    }

    public static function getReply($command, $role = 'asesor')
    {
        $replies = self::getReplies($role);
        return $replies[$command] ?? null;
    }
}